services:
  - type: web
    name: employee-portal-backend
    env: python
    plan: starter
    region: oregon
    buildCommand: cd backend && uv sync
    startCommand: cd backend && uv run uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: CORS_ORIGINS
        value: '["https://your-frontend-domain","http://localhost:3000"]'
      - key: DATABASE_URL
        fromDatabase: kuberya-attendance-db

databases:
  - name: kuberya-attendance-db
    plan: starter
    postgresVersion: 15
